# Generated by Django 5.0.4 on 2024-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('device_issue', models.TextField()),
                ('serial_number', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('device_image', models.ImageField(blank=True, null=True, upload_to='device_images/')),
            ],
        ),
    ]
